apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pool.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "auth.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "auth.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--repo", {{ $.Values.arguments.repo }},  "run"]
          ports:
            - name: http
              containerPort: 8989
              protocol: TCP
{{/*
          livenessProbe:
            httpGet:
              path: "/tokens?skip=0&limit=10"
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: "/tokens?skip=0&limit=10"
              port: http
            initialDelaySeconds: 60
*/}}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          volumeMounts:
          - name: data
            mountPath: {{ $.Values.volumes.mountpathData }}
      {{- with .Values.pool.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pool.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pool.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: auth
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: {{ $.Values.pool.storage }}

