apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-cupid-proofparams
spec:
  capacity:
    storage: 300Gi
  volumeMode: Filesystem
  storageClassName: proofparams
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /media/ssd1/nfs/cupid/paramcache
    server: 66.220.22.35
