apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-cupid-venus
spec:
  capacity:
    storage: 800Gi
  volumeMode: Filesystem
  storageClassName: venus
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /media/ssd1/nfs/cupid/venus
    server: 66.220.22.35
