apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-cupid-auth
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: auth
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /media/ssd1/nfs/cupid/auth
    server: 66.220.22.35
