apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-cupid-proofparams
spec:
  capacity:
    storage: 300Gi
  volumeMode: Filesystem
  storageClassName: proofparams
  accessModes:
   - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/tmp/filecoin-proof-parameters
    server: 66.220.22.35
