apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cupid-local-miner5
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cupid-local-miner5
  local:
    path: /media/ssd2/cupid
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - miner5
