apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-cupid
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /media/ssd1/nfs/cupid
    server: 66.220.22.35
