apiVersion: v1
kind: Service
metadata:
  name: {{ include "venus.fullname" . }}
  labels:
    {{- include "venus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort:  {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "venus.selectorLabels" . | nindent 4 }}
