apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cupid.fullname" . }}-miner
  labels:
    {{- include "cupid.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.miner.pool.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cupid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cupid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cupid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.miner.image.repository }}:{{ .Values.miner.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.miner.image.pullPolicy }}
          args:          
            {{-  range .Values.miner.arguments }}
            - {{ . }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3453
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.miner.agent.resources | nindent 12 }}
      {{- with .Values.miner.pool.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.miner.pool.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.miner.pool.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
